#!/bin/bash

# Configuration variables passed from docker run
DELAY=${DELAY:-0ms}
LOSS=${LOSS:-0%}
RATE=${RATE:-1000mbit}
OUTPUT_FILE=${OUTPUT_FILE:-bench_results.csv}

echo "Applying Traffic Control (tc) settings..."
echo "  Delay: $DELAY"
echo "  Loss: $LOSS"
echo "  Rate limit: $RATE"

# Verify basic internet connectivity before shaping
echo "Verifying internet connectivity for DHT bootstrap..."
if ! ping -c 1 router.bittorrent.com > /dev/null 2>&1; then
    echo "WARNING: Cannot reach DHT bootstrap nodes. Benchmarks may fail."
fi

# Clear existing rules just in case
tc qdisc del dev eth0 root 2> /dev/null

# Apply the new network constraints to eth0
# We use a token bucket filter (tbf) for rate limiting, and netem for delay/loss.
tc qdisc add dev eth0 root handle 1: tbf rate $RATE burst 32kbit latency 400ms
tc qdisc add dev eth0 parent 1:1 handle 10: netem delay $DELAY loss $LOSS

echo "Network shaped successfully. Starting benchmark..."

cd /usr/src/gossip

# Ensure config is available in common places
mkdir -p config
cp bench_config.ron config/ 2>/dev/null || true

# Run the pre-compiled orchestrator binary directly
./target/release/bench_orchestrator

# Copy the results to the mounted volume if it exists
if [ -f "bench_results.csv" ]; then
    if [ -d "/results" ]; then
        cp bench_results.csv "/results/$OUTPUT_FILE"
        echo "Results copied to host machine as $OUTPUT_FILE"
    else
        echo "WARNING: /results directory not mounted. Data is trapped in the container."
    fi
else
    echo "ERROR: bench_results.csv was not generated by the orchestrator."
    exit 1
fi
